files: ^tests/|^tp1/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/psf/black.git
    rev: 22.8.0
    hooks:
      - id: black
        name: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
